import { Entry } from "./entry";
import { Categories } from "./category";

export var DefaultOptions: Entry[] = [
  // Life Partner
  new Entry(Categories[0], 0, "A Baron", true),
  new Entry(Categories[0], 0, "A Baroness", true),
  new Entry(Categories[0], 0, "A Count", true),
  new Entry(Categories[0], 0, "A Countess", true),
  new Entry(Categories[0], 0, "The King", true),
  new Entry(Categories[0], 0, "The Queen", true),
  new Entry(Categories[0], 0, "Three Racoons in a Trenchcoat", true),
  new Entry(Categories[0], 0, "The Pope", true),
  new Entry(Categories[0], 0, "The President", true),
  new Entry(Categories[0], 0, "The Prime Minister", true),
  new Entry(Categories[0], 0, "Your Teacher", true),
  new Entry(Categories[0], 0, "Your Boss", true),
  new Entry(Categories[0], 0, "Your Doctor", true),
  new Entry(Categories[0], 0, "Your Lawyer", true),
  new Entry(Categories[0], 0, "Your Dentist", true),

  new Entry(Categories[0], 0, "Your Therapist", true),
  new Entry(Categories[0], 0, "Your Barista", true),
  new Entry(Categories[0], 0, "Mother Goose", true),
  new Entry(Categories[0], 0, "Old King Cole", true),
  new Entry(Categories[0], 0, "Old Mother Hubbard", true),
  new Entry(Categories[0], 0, "Little Bo Peep", true),
  new Entry(Categories[0], 0, "Humpty Dumpty", true),
  new Entry(Categories[0], 0, "Jack and Jill", true),
  new Entry(Categories[0], 0, "Little Miss Muffet", true),
  new Entry(Categories[0], 0, "The Queen of Hearts", true),
  new Entry(Categories[0], 0, "Tom, Tom, the Piper's Son", true),
  new Entry(Categories[0], 0, "Peter, Peter, Pumpkin Eater", true),
  new Entry(Categories[0], 0, "Simple Simon", true),
  new Entry(Categories[0], 0, "Wee Willie Winkie", true),
  new Entry(Categories[0], 0, "Little Boy Blue", true),
  new Entry(Categories[0], 0, "The Grand Old Duke of York", true),
  new Entry(Categories[0], 0, "The Muffin Man", true),
  new Entry(Categories[0], 0, "John Lennon", true),
  new Entry(Categories[0], 0, "Jimi Hendrix", true),
  new Entry(Categories[0], 0, "Freddie Mercury", true),
  new Entry(Categories[0], 0, "Kurt Cobain", true),
  new Entry(Categories[0], 0, "Elvis Presley", true),
  new Entry(Categories[0], 0, "Janis Joplin", true),
  new Entry(Categories[0], 0, "Jim Morrison", true),
  new Entry(Categories[0], 0, "Amy Winehouse", true),
  new Entry(Categories[0], 0, "Bob Marley", true),
  new Entry(Categories[0], 0, "George Harrison", true),
  new Entry(Categories[0], 0, "David Bowie", true),
  new Entry(Categories[0], 0, "Prince", true),
  new Entry(Categories[0], 0, "Tom Petty", true),
  new Entry(Categories[0], 0, "Roy Orbison", true),
  new Entry(Categories[0], 0, "Johnny Cash", true),
  new Entry(Categories[0], 0, "Luke Skywalker", true),
  new Entry(Categories[0], 0, "Princess Leia", true),
  new Entry(Categories[0], 0, "Han Solo", true),
  new Entry(Categories[0], 0, "Ellen Ripley", true),
  new Entry(Categories[0], 0, "Spock", true),
  new Entry(Categories[0], 0, "Sarah Connor", true),
  new Entry(Categories[0], 0, "Jean-Luc Picard", true),
  new Entry(Categories[0], 0, "Dana Scully", true),
  new Entry(Categories[0], 0, "River Song", true),
  new Entry(Categories[0], 0, "Captain Kirk", true),
  new Entry(Categories[0], 0, "Katniss Everdeen", true),
  new Entry(Categories[0], 0, "Neo", true),
  new Entry(Categories[0], 0, "Trinity", true),
  new Entry(Categories[0], 0, "Captain Marvel", true),
  new Entry(Categories[0], 0, "Catherine Gale", true),
  new Entry(Categories[0], 0, "Dr. Paul Morrow", true),
  new Entry(Categories[0], 0, "Emma Peel", true),
  new Entry(Categories[0], 0, "Professor Bernard Quatermass", true),
  new Entry(Categories[0], 0, "John Koenig", true),
  new Entry(Categories[0], 0, "Annie Crozier", true), // "Timeslip" (1970-1971)
  new Entry(Categories[0], 0, "John Steed", true), // "The Avengers" (1961-1969)
  new Entry(Categories[0], 0, "Samantha Briggs", true),
  new Entry(Categories[0], 0, "Sandra Benes", true),
  new Entry(Categories[0], 0, "Aunt Harriet", true),
  // Job
  new Entry(Categories[1], 0, "Dentist", true),
  new Entry(Categories[1], 0, "Veterinarian", true),
  new Entry(Categories[1], 0, "Doctor", true),
  new Entry(Categories[1], 0, "Lawyer", true),
  new Entry(Categories[1], 0, "Teacher", true),
  new Entry(Categories[1], 0, "Janitor", true),
  new Entry(Categories[1], 0, "Politician", true),
  new Entry(Categories[1], 0, "President", true),
  new Entry(Categories[1], 0, "Prime Minister", true),
  new Entry(Categories[1], 0, "Astronaut", true),
  new Entry(Categories[1], 0, "Scientist", true),
  new Entry(Categories[1], 0, "Engineer", true),
  new Entry(Categories[1], 0, "Programmer", true),
  new Entry(Categories[1], 0, "Artist", true),
  new Entry(Categories[1], 0, "Musician", true),
  new Entry(Categories[1], 0, "Writer", true),
  new Entry(Categories[1], 0, "Chef", true),
  new Entry(Categories[1], 0, "Baker", true),
  new Entry(Categories[1], 0, "Barista", true),
  new Entry(Categories[1], 0, "Waiter", true),
  new Entry(Categories[1], 0, "Bartender", true),
  new Entry(Categories[1], 0, "Bus Driver", true),
  new Entry(Categories[1], 0, "Truck Driver", true),
  new Entry(Categories[1], 0, "Pilot", true),
  new Entry(Categories[1], 0, "Flight Attendant", true),
  new Entry(Categories[1], 0, "Police Officer", true),
  new Entry(Categories[1], 0, "Firefighter", true),
  new Entry(Categories[1], 0, "Fire Truck", true),
  new Entry(Categories[1], 0, "Rock Star", true),
  new Entry(Categories[1], 0, "Movie Star", true),
  new Entry(Categories[1], 0, "TV Star", true),
  new Entry(Categories[1], 0, "Crossing Guard", true),
  new Entry(Categories[1], 0, "Mail Carrier", true),
  new Entry(Categories[1], 0, "Sanitation Worker", true),
  new Entry(Categories[1], 0, "Military General", true),
  // Car
  new Entry(Categories[2], 0, "Porsche", true),
  new Entry(Categories[2], 0, "Ferrari", true),
  new Entry(Categories[2], 0, "Lamborghini", true),
  new Entry(Categories[2], 0, "Bugatti", true),
  new Entry(Categories[2], 0, "Tesla", true),
  new Entry(Categories[2], 0, "Toyota", true),
  new Entry(Categories[2], 0, "Honda", true),
  new Entry(Categories[2], 0, "Ford", true),
  new Entry(Categories[2], 0, "Chevrolet", true),
  new Entry(Categories[2], 0, "Dodge", true),
  new Entry(Categories[2], 0, "Jeep", true),
  new Entry(Categories[2], 0, "Subaru", true),
  new Entry(Categories[2], 0, "Volkswagen", true),
  new Entry(Categories[2], 0, "Audi", true),
  new Entry(Categories[2], 0, "BMW", true),
  new Entry(Categories[2], 0, "Mercedes", true),
  new Entry(Categories[2], 0, "Lexus", true),
  new Entry(Categories[2], 0, "Infiniti", true),
  new Entry(Categories[2], 0, "Acura", true),
  new Entry(Categories[2], 0, "Maserati", true),
  new Entry(Categories[2], 0, "Alfa Romeo", true),
  new Entry(Categories[2], 0, "Jaguar", true),
  new Entry(Categories[2], 0, "Land Rover", true),
  new Entry(Categories[2], 0, "Range Rover", true),
  new Entry(Categories[2], 0, "Bentley", true),
  new Entry(Categories[2], 0, "Rolls Royce", true),
  new Entry(Categories[2], 0, "McLaren", true),
  new Entry(Categories[2], 0, "Koenigsegg", true),
  new Entry(Categories[2], 0, "Pagani", true),
  new Entry(Categories[2], 0, "Lotus", true),
  new Entry(Categories[2], 0, "Mazda", true),
  new Entry(Categories[2], 0, "Nissan", true),
  new Entry(Categories[2], 0, "Mitsubishi", true),
  new Entry(Categories[2], 0, "Kia", true),
  new Entry(Categories[2], 0, "Hyundai", true),
  new Entry(Categories[2], 0, "Wheelbarrow", true),
  new Entry(Categories[2], 0, "Bicycle", true),
  new Entry(Categories[2], 0, "Tricycle", true),
  new Entry(Categories[2], 0, "Unicycle", true),
  new Entry(Categories[2], 0, "Scooter", true),
  new Entry(Categories[2], 0, "Skateboard", true),
  new Entry(Categories[2], 0, "Rollerblade", true),
  new Entry(Categories[2], 0, "Rollerskate", true),
  new Entry(Categories[2], 0, "Segway", true),
  new Entry(Categories[2], 0, "Hoverboard", true),
  new Entry(Categories[2], 0, "Jetpack", true),
  new Entry(Categories[2], 0, "Helicopter", true),
  new Entry(Categories[2], 0, "Airplane", true),
  new Entry(Categories[2], 0, "Spaceship", true),
  new Entry(Categories[2], 0, "Hot Air Balloon", true),
  new Entry(Categories[2], 0, "Zeppelin", true),
  new Entry(Categories[2], 0, "Tank", true),
  new Entry(Categories[2], 0, "Submarine", true),
  new Entry(Categories[2], 0, "Yacht", true),
  new Entry(Categories[2], 0, "Speedboat", true),
  new Entry(Categories[2], 0, "Sailboat", true),
  new Entry(Categories[2], 0, "Canoe", true),
  new Entry(Categories[2], 0, "Kayak", true),
  new Entry(Categories[2], 0, "Rowboat", true),
  new Entry(Categories[2], 0, "Pair of Heelies", true),
  new Entry(Categories[2], 0, "Teleporter", true),
  new Entry(Categories[2], 0, "Time Machine", true),
  new Entry(Categories[2], 0, "Magic Carpet", true),
  new Entry(Categories[2], 0, "Horse", true),
  new Entry(Categories[2], 0, "Unicorn", true),
  new Entry(Categories[2], 0, "Pegasus", true),
  new Entry(Categories[2], 0, "Dragon", true),
  // Pet
  new Entry(Categories[3], 0, "Dog", true),
  new Entry(Categories[3], 0, "Cat", true),
  new Entry(Categories[3], 0, "Fish", true),
  new Entry(Categories[3], 0, "Bird", true),
  new Entry(Categories[3], 0, "Rabbit", true),
  new Entry(Categories[3], 0, "Hamster", true),
  new Entry(Categories[3], 0, "Guinea Pig", true),
  new Entry(Categories[3], 0, "Ferret", true),
  new Entry(Categories[3], 0, "Hedgehog", true),
  new Entry(Categories[3], 0, "Turtle", true),
  new Entry(Categories[3], 0, "Snake", true),
  new Entry(Categories[3], 0, "Lizard", true),
  new Entry(Categories[3], 0, "Chameleon", true),
  new Entry(Categories[3], 0, "Gecko", true),
  new Entry(Categories[3], 0, "Iguana", true),
  new Entry(Categories[3], 0, "Bearded Dragon", true),
  new Entry(Categories[3], 0, "Tarantula", true),
  new Entry(Categories[3], 0, "Scorpion", true),
  new Entry(Categories[3], 0, "Hermit Crab", true),
  new Entry(Categories[3], 0, "Ant Farm", true),
  new Entry(Categories[3], 0, "Sea Monkey", true),
  new Entry(Categories[3], 0, "Mouse", true),
  new Entry(Categories[3], 0, "Rat", true),
  new Entry(Categories[3], 0, "Gerbil", true),
  new Entry(Categories[3], 0, "Parrot", true),
  new Entry(Categories[3], 0, "Sasquatch", true),
  new Entry(Categories[3], 0, "Bigfoot", true),
  new Entry(Categories[3], 0, "Yeti", true),
  new Entry(Categories[3], 0, "Loch Ness Monster", true),
  new Entry(Categories[3], 0, "Chupacabra", true),
  new Entry(Categories[3], 0, "Kraken", true),
  new Entry(Categories[3], 0, "Mothman", true),
  new Entry(Categories[3], 0, "Jersey Devil", true),
  new Entry(Categories[3], 0, "Thunderbird", true),
  new Entry(Categories[3], 0, "Jackalope", true),
  new Entry(Categories[3], 0, "Lion", true),
  new Entry(Categories[3], 0, "Tiger", true),
  new Entry(Categories[3], 0, "Bear", true),
  new Entry(Categories[3], 0, "Wolf", true),
  new Entry(Categories[3], 0, "Fox", true),
  new Entry(Categories[3], 0, "Coyote", true),
  new Entry(Categories[3], 0, "Raccoon", true),
  new Entry(Categories[3], 0, "Skunk", true),
  new Entry(Categories[3], 0, "Squirrel", true),
  new Entry(Categories[3], 0, "Chipmunk", true),
  new Entry(Categories[3], 0, "Opossum", true),
  new Entry(Categories[3], 0, "Badger", true),
  new Entry(Categories[3], 0, "Beaver", true),
  new Entry(Categories[3], 0, "Otter", true),
  new Entry(Categories[3], 0, "Seal", true),
  new Entry(Categories[3], 0, "Walrus", true),
  new Entry(Categories[3], 0, "Penguin", true),
  new Entry(Categories[3], 0, "Puffin", true),
  new Entry(Categories[3], 0, "Horse", true),
  new Entry(Categories[3], 0, "Unicorn", true),
  new Entry(Categories[3], 0, "Pegasus", true),
  new Entry(Categories[3], 0, "Dragon", true),
  new Entry(Categories[3], 0, "Three Racoons in a Trenchcoat", true),
  // House
  new Entry(Categories[4], 0, "A Mansion", true),
  new Entry(Categories[4], 0, "A Castle", true),
  new Entry(Categories[4], 0, "A Palace", true),
  new Entry(Categories[4], 0, "A Cabin", true),
  new Entry(Categories[4], 0, "A Cottage", true),
  new Entry(Categories[4], 0, "A Tent", true),
  new Entry(Categories[4], 0, "An RV", true),
  new Entry(Categories[4], 0, "A Treehouse", true),
  new Entry(Categories[4], 0, "An Apartment", true),
  new Entry(Categories[4], 0, "A Condo", true),
  new Entry(Categories[4], 0, "A Townhouse", true),
  new Entry(Categories[4], 0, "A Duplex", true),
  new Entry(Categories[4], 0, "A Triplex", true),
  new Entry(Categories[4], 0, "A Fourplex", true),
  new Entry(Categories[4], 0, "A Studio", true),
  new Entry(Categories[4], 0, "A Loft", true),
  new Entry(Categories[4], 0, "A Flat", true),
  new Entry(Categories[4], 0, "A Penthouse", true),
  new Entry(Categories[4], 0, "A Shack", true),
  new Entry(Categories[4], 0, "A Lean-To", true),
  new Entry(Categories[4], 0, "A Yurt", true),
  new Entry(Categories[4], 0, "A Teepee", true),
  new Entry(Categories[4], 0, "A Igloo", true),
  new Entry(Categories[4], 0, "A Cave", true),
  new Entry(Categories[4], 0, "A Burrow", true),
  new Entry(Categories[4], 0, "A Hole in the Ground", true),
  new Entry(Categories[4], 0, "The T.A.R.D.I.S.", true),
  new Entry(Categories[4], 0, "A Moon Base", true),
  new Entry(Categories[4], 0, "A Space Station", true),
  new Entry(Categories[4], 0, "An Underwater Base", true),
  new Entry(Categories[4], 0, "A Floating Island", true),
  new Entry(Categories[4], 0, "A Cloud Castle", true),
  new Entry(Categories[4], 0, "A Sky Palace", true),
  new Entry(Categories[4], 0, "A Sky Scraper", true),
  new Entry(Categories[4], 0, "A Bungalow", true),
  new Entry(Categories[4], 0, "A Ranch", true),
  new Entry(Categories[4], 0, "A Farm", true),
  new Entry(Categories[4], 0, "Howl's Moving Castle", true),
  new Entry(Categories[4], 0, "Bag End, Bagshot Row, Hobbiton", true),
  new Entry(Categories[4], 0, "221B Baker Street, London", true),
  new Entry(Categories[4], 0, "Pemberley, Derbyshire", true),
  new Entry(Categories[4], 0, "Thornfield Hall", true),
  new Entry(Categories[4], 0, "Manderley", true),
  new Entry(Categories[4], 0, "Satis House, Rochester", true),
  new Entry(Categories[4], 0, "Green Gables, Avonlea", true),
  new Entry(Categories[4], 0, "Brideshead Castle, Wiltshire", true),
  new Entry(Categories[4], 0, "The Overlook Hotel", true),
  new Entry(Categories[4], 0, "7 Eccles Street, Dublin", true),
  new Entry(Categories[4], 0, "Villa Villekulla", true),
  new Entry(
    Categories[4],
    0,
    "House of the Seven Gables, Salem, Massachusetts",
    true,
  ),
  new Entry(Categories[4], 0, "Jurassic Park, Isla Nublar", true),
  new Entry(Categories[4], 0, "Castle Dracula, Transylvania", true),
  new Entry(Categories[4], 0, "Misselthwaite Manor, Yorkshire", true),
  new Entry(Categories[4], 0, "The Little House, Plumfield Estate", true),
  new Entry(Categories[4], 0, "Donnafugata Castle", true),
  new Entry(Categories[4], 0, "Malfoy Manor", true),
  new Entry(Categories[4], 0, "Wuthering Heights", true),
  new Entry(Categories[4], 0, "4 Privet Drive, Little Whinging", true),
];
